# Generated by Django 4.1.3 on 2022-11-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='x1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post1',
            name='x3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post1',
            name='x4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
